variables:
  CCACHE_DIR: ${CI_PROJECT_DIR}/ccache
  CCACHE_MAXSIZE: 2G
  CCACHE_KEY_SUFFIX: r1
  CTEST_OUTPUT_ON_FAILURE: 1

macos-arm:
  stage: build
  tags:
    - macos-arm64
  before_script:
    - hostname
    - whoami
    - pwd
    - echo ${CI_PROJECT_DIR}


  script:
    - git clone $CLONE_URL src

    - cd src
    - git checkout $HEAD_SHA
    - git submodule init
    - git submodule update

    - cd ..
    - mkdir build
    - >
      cmake -B build -S src
      -GNinja
      -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
      -DCMAKE_BUILD_TYPE=RelWithDebInfo
      -DCMAKE_CXX_FLAGS=-Werror
      -DCMAKE_CXX_STANDARD=17
      -DACTS_ENABLE_LOG_FAILURE_THRESHOLD=ON
      -DACTS_BUILD_UNITTESTS=ON

    - ccache -z
    - cmake --build build
    - ccache -s

    - cmake --build build --target test
