variables:
  CCACHE_DIR: ${CI_PROJECT_DIR}/ccache
  CCACHE_MAXSIZE: 2G
  CCACHE_KEY_SUFFIX: r1
  CTEST_OUTPUT_ON_FAILURE: 1

macos-arm:
  stage: build
  tags:
    - macos-arm64
  script:
    - hostname
    - whoami
    - pwd
    - echo ${CI_PROJECT_DIR}
    - date > output.txt

