variables:
  CCACHE_DIR: ${CI_PROJECT_DIR}/ccache
  CCACHE_MAXSIZE: 10G
  CCACHE_KEY_SUFFIX: r1

build_exatrkx:
  stage: build
  image: ghcr.io/acts-project/ubuntu2004_exatrkx:v41
  tags:
    - docker

  cache:
    key: ccache-exatrkx-$CI_COMMIT_REF_SLUG
    paths:
      - ${CI_PROJECT_DIR}/ccache_${CCACHE_KEY_SUFFIX}

  artifacts:
    paths:
      - build/
    exclude:
      - build/**/*.o
      - build/bin/ActsUnitTest*
      - build/bin/ActsIntegrationTest*

  script:
    - export PATH=/usr/local/sbin:/usr/sbin:/sbin:$PATH
    - export PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:$PATH
    - echo $PATH
    - git clone $CLONE_URL src
    - cd src
    - git checkout $HEAD_SHA
    - cd ..
    - mkdir build
    - >
      cmake -B build -S src
      -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
      -GNinja
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_CXX_FLAGS=-w
      -DCMAKE_CUDA_FLAGS=-w
      -DCMAKE_CUDA_ARCHITECTURES="75;86"
      -DACTS_BUILD_PLUGIN_EXATRKX=ON
      -DACTS_BUILD_EXAMPLES_EXATRKX=ON
      -DACTS_EXATRKX_ENABLE_TORCH=ON
      -DACTS_EXATRKX_ENABLE_ONNX=ON
      -DACTS_BUILD_EXAMPLES_PYTHON_BINDINGS=ON
      -DACTS_ENABLE_LOG_FAILURE_THRESHOLD=ON
    - cmake --build build --

test_exatrkx:
  stage: test
  needs:
    - build_exatrkx
  image: ghcr.io/acts-project/ubuntu2004_exatrkx:v41
  tags:
    - docker-gpu-nvidia
  script:
    - apt-get update -y
    - apt-get install -y python3 libxxhash0
    - source /usr/local/bin/thisroot.sh
    - source build/python/setup.sh
    - git clone $CLONE_URL src
    - cd src
    - git checkout $HEAD_SHA
    - pip3 install -r Examples/Python/tests/requirements.txt
    - nvidia-smi
    - pytest -rFsv -k test_exatrkx

