# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

container: gitlab-registry.cern.ch/acts/machines/ubuntu2004:master

steps:
  - displayName: Configure
    script: >
      cmake -B build -S .
      -GNinja
      -DCMAKE_BUILD_TYPE=Debug
      -DCMAKE_CXX_FLAGS=-Werror
      -DACTS_BUILD_DD4HEP_PLUGIN=off
      -DACTS_BUILD_DIGITIZATION_PLUGIN=on
      -DACTS_BUILD_IDENTIFICATION_PLUGIN=on
      -DACTS_BUILD_JSON_PLUGIN=on
      -DACTS_BUILD_TGEO_PLUGIN=on
      -DACTS_BUILD_LEGACY=on
      -DACTS_BUILD_FATRAS=on
      -DACTS_BUILD_BENCHMARKS=on
      -DACTS_BUILD_UNITTESTS=on

  - displayName: Build
    script: cmake --build build --

  - displayName: Unit tests
    script: cmake --build build -- test

  - displayName: Coverage
    script: >
      pip3 install gcovr
      && cd build
      && /usr/bin/python3 ../CI/test_coverage

  - displayName: 'Upload to codecov.io'
    script: bash <(curl -s https://codecov.io/bash)

