[[whitepapers]]
repository = "https://github.com/acts-project/whitepaper-template"

[whitepapers.metadata]
authors = [ "First Author", "Second Author",]
title = "A whitepaper about a topic"
description = "This is a whitepaper example. It contains a number of example\npatterns, layouts etc."
