name: Check PR labels

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

jobs:
  check_pr_labels:
    name: Check PR Labels
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v3
      - name: labeler
        uses: uses: actions/labeler@v4
	Infrastructure:
	  - aby: ['.github/**', 'CI/**']
